### ISSUE TITLE
Add support for ERC20/ERC721 contracts generated by OpenZeppelin

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly-tokens-erc20-erc721#90]
OpenZeppelin provides a contract wizard for generating common token contracts:
https://docs.openzeppelin.com/contracts/4.x/wizard

The method names and signatures in these contracts (for things like mint/transfer/burn) differ slightly from the samples already checked into this repository. We should add support for these in the ABI map here:
https://github.com/hyperledger/firefly-tokens-erc20-erc721/blob/b2aa707b4ddc58a101af3eaf81dddb13a7c805c1/src/tokens/tokens.service.ts#L111
Note that most/all of these methods may not include extra "data" arguments, so FireFly will not be able to write extra data to the chain (such as transaction and message IDs) when using these contracts - this is accepted as a known limitation.

**Comment by awrichar** [comment]
Also note concerns with the existing naming of sample schemas, as detailed in #63

**Comment by nguyer** [comment]
Resolved in https://github.com/hyperledger/firefly-tokens-erc20-erc721/pull/104
